#index:
#    path: /
#    controller: App\Controller\DefaultController::index


# config/routes.yaml
dashboard:
    path: /dashboard
    controller: App\Controller\DashboardController::index

student:
    path: /student
    controller: App\Controller\StudentController::index


retake:
    path: /activity/retake/{id}
    controller: App\Controller\StudentController::retake

showallactivities:
    path: /subject/activities/{id}
    controller:  App\Controller\SubjectsController::showSubmission

    
grading:
    path: /grading
    controller: App\Controller\GradingController::index
    
profile:
    path: /profile
    controller: App\Controller\ProfileController::index
    
viewStudent:
    path: /student/mystudent/{id}
    controller: App\Controller\StudentController::view
    
subjects:
    path: /subjects
    controller: App\Controller\SubjectsController::index
    
viewSubjects:
    path: /subjects/{id}
    controller: App\Controller\SubjectsController::view
    defaults: { id: 1 }

removeActivity:
    path: /subjects/api/removeActivity
    controller:  App\Controller\SubjectsController::removeActivity
    options:
        expose: true
grades:
    path: /grades
    controller: App\Controller\GradingController::showMyGrades
    
classrooms:
    path: /classrooms
    controller: App\Controller\SubjectsController::showClassrooms
    
gradeStudent:
    path: /grading/grade/{id}
    controller: App\Controller\GradingController::gradeStudent
showClassroom:
    path: /classroom/activities/{id}
    controller: App\Controller\SubjectsController::showClassroom
showClassroomModule:
    path: /classroom/module/{id}
    controller: App\Controller\SubjectsController::showClassroomModule



showClassroomActivities:
    path: /classroom/activities/activityID/{id}
    controller: App\Controller\StudentController::showClassroomActivity

showUploadPayment:
    path: /profile/uploadpayment
    controller: App\Controller\StudentController::showUploadPayment

getUploadedFile:
    path: /student/getFile
    controller: App\Controller\SubjectsController::retriveFile
showstudentactivity:
    path: /activity/view/{id}
    controller: App\Controller\SubjectsController::showActivityView

addActivity:
    path: /subjects/api/addActivity
    controller:  App\Controller\SubjectsController::addActivity
    options:
        expose: true
submitActivity:
    path: /student/submitActivity
    controller: App\Controller\StudentController::submitActivity
    options:
        expose: true
addReceipt:
    path: /students/api/uploadPayment
    controller:  App\Controller\StudentController::uploadReceipt
    options:
        expose: true
addpoints:
    path: /students/api/addpoints
    controller:  App\Controller\SubjectsController::addPoints
    options:
        expose: true