#index:
#    path: /
#    controller: App\Controller\DefaultController::index


# config/routes.yaml
dashboard:
    path: /dashboard
    controller: App\Controller\DashboardController::index
student:
  path: /student
  controller: App\Controller\StudentController::index

grading:
    path: /grading
    controller: App\Controller\GradingController::index
profile:
    path: /profile
    controller: App\Controller\ProfileController::index
viewStudent:
    path: /student/mystudent/{id}
    controller: App\Controller\StudentController::view
subjects:
    path: /subjects
    controller: App\Controller\SubjectsController::index
viewSubjects:
    path: /subjects/{id}
    controller: App\Controller\SubjectsController::view
addActivity:
    path: /subjects/api/addActivity
    controller:  App\Controller\SubjectsController::addActivity
gradeStudent:
    path: /grading/grade/{id}?course={course}&fullname={fullname}
    controller: App\Controller\GradingController::gradeStudent
